export const StartupsData = [
  {
    name: "starks",
    image: "starks",
    hasLabel: true,
    title: "Starks Associate",
    handle: "John, Management",
    desc: "Partnering with Forcythe was like finding a hidden gem. Their genuine interest in our success was palpable, and the continuous support post-launch has been a testament to their commitment. They've become more than a service provider; they're a trusted ally.",
    handleImage: "john",
  },
  {
    name: "ExecutivePros Logo",
    image: "ExecutivePros Logo",
    title: "ExecutivePros",
    handle: "Testimony, Co-founder",
    desc: "The team understood the assignment and delivered very well. One of the things that stood them out was how they took our concepts and turned it into visually appealing designs that caught the eyes of our clients and made increased web engagements. Kudos!",
    handleImage: "executive-pro-ceo",
  },
  {
    name: "stacai",
    image: "stacai",
    title: "Stac AI",
    handle: "Edwin, Former CTO",
    desc: "Forcythe is seriously amazing when it comes to coming up with new ideas. They took our rough ideas and turned them into something incredible online. Their team's commitment to our vision was evident every step of the way.",
    handleImage: "edwin",
  },
  {
    name: "iwaria",
    image: "iwaria",
    title: "Iwaria",
    handle: "Iwaria, Founder",
    desc: "The moment we engaged Forcythe, it was clear they were in a league of their own. Their strategic approach to our project not only enhanced our online platform but also enriched our brand's story, captivating our audience like never before.",
    handleImage: "iwaria-founder",
  },
  {
    name: "Beaupreneur",
    image: "Beaupreneur",
    title: "Beaupreneur",
    handle: "Christiana, Founder",
    desc: "I'm beyond impressed with the dedication Forcythe showed. They didn't just deliver, they educated us, involving us in the creative process. The result? A website that truly feels like ours and speaks directly to our customers' hearts.",
    handleImage: "christina",
  },
];
